# Project
spring.application.name=coupon-rush
# Database: PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coupon_rush
spring.datasource.username=couponrush
spring.datasource.password=couponrush
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=coupon-rush
security.jwt.access-token-expiration-seconds=3600