# Project
spring.application.name=coupon-rush
# Database: PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coupon_rush
spring.datasource.username=couponrush
spring.datasource.password=couponrush
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true